// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoOfa74K9XHRROxr6Oy6T1w_dP0UY_-tc',
    appId: '1:7869757307:web:bd61bc5ed4f7620948afde',
    messagingSenderId: '7869757307',
    projectId: 'tipzy-dc078',
    authDomain: 'tipzy-dc078.firebaseapp.com',
    storageBucket: 'tipzy-dc078.appspot.com',
    measurementId: 'G-LJRXEY268Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM3dFHsWrPJqKZAAi-_2RDQSQSeV78hiM',
    appId: '1:7869757307:android:a2c6b1fc79e8425748afde',
    messagingSenderId: '7869757307',
    projectId: 'tipzy-dc078',
    storageBucket: 'tipzy-dc078.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPFWfxmiQhQv-67sm9YYddi7Q_8kHZcAQ',
    appId: '1:7869757307:ios:7dcfd2ca2bb6ba6048afde',
    messagingSenderId: '7869757307',
    projectId: 'tipzy-dc078',
    storageBucket: 'tipzy-dc078.appspot.com',
    androidClientId: '7869757307-vt2urtjd9o0guhh4kf399juhgv3jlqi4.apps.googleusercontent.com',
    iosClientId: '7869757307-ihd8tcf8pmh31abtf79rh4qjtm43r2h9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tipzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPFWfxmiQhQv-67sm9YYddi7Q_8kHZcAQ',
    appId: '1:7869757307:ios:442f0d407899311a48afde',
    messagingSenderId: '7869757307',
    projectId: 'tipzy-dc078',
    storageBucket: 'tipzy-dc078.appspot.com',
    androidClientId: '7869757307-vt2urtjd9o0guhh4kf399juhgv3jlqi4.apps.googleusercontent.com',
    iosClientId: '7869757307-26q8n6uj2rnou2dmett1ih3nahgqq0ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.tipzy.RunnerTests',
  );
}
